// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auvimrxyqfprotetusxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1dmltcnh5cWZwcm90ZXR1c3hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjY1MjIsImV4cCI6MjA2NTE0MjUyMn0.6jXCzyrOqAJubCqxLtxBaEaoCKciU0nE_VcCHNE-gWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);